#!/usr/bin/env bash
# Script that displays information about domains and subdomains
# shellcheck disable=SC2086

parse ()
{
	dig +noall +answer "$2.$1" | awk '{printf "The subdomain %s is a %s record and points to %s\n", var, $4, $5}' var="subdomain"
}

for subdomain in "www" "lb-01" "web-01" "web-02"
do
	if [ -z "$2" ] || [ "$2" == "$subdomain" ] ;
	then
		parse "$1" "$subdomain"
	fi
done
