#!/usr/bin/env bash
# Install nginx on your server
sudo apt-get update -y
sudo apt-get upgrade -y
sudo apt-get install nginx -y
sudo echo "Hello World!" | sudo tee "/var/www/html/index.html"
sudo service nginx restart
