#!/usr/bin/env bash
# Configure your Nginx server so that /redirect_me is redirecting to another page
#sudo apt-get update -y
#sudo apt-get upgrade -y
#sudo apt-get install nginx -y
#echo "Hello World!" | sudo tee "/var/www/html/index.html"
#sudo sed -i "/server_name _;/a \\\trewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;" /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" | sudo tee "/var/www/html/404.html"
new_string="\\\terror_page 404 /404.html;\n\tlocation = /404.html {\n\t\troot /var/www/html;\n\t\tinternal;\n\t}"
sudo sed -i "25i $new_string" /etc/nginx/sites-available/default
sudo service nginx restart
