#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server
sudo apt-get update -y
sudo apt-get upgrade -y
sudo apt-get install haproxy -y
sudo sed -i '$ aENABLED=1/' /etc/default/haproxy
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.original
sed -i '$ a\\nfrontend haproxynode\n\tbind *:80\n\tmode http\n\tdefault_backend backendnodes' /etc/haproxy/haproxy.cfg
sed -i '$ a\\nbackend backendnodes\n\tbalance roundrobin\n\tserver 2654-web-01 34.73.111.76:8080 check\n\tserver 2654-web-02 184.72.74.246:8080 check' /etc/haproxy/haproxy.cfg
sudo service haproxy start
