#!/usr/bin/env bash
# Script that displays: "to infinity..." and I am invincible when catch term sig
trap "echo 'I am invincible!!!'" SIGTERM
while ((1))
do
	echo "To infinity and beyond"
	sleep 2
done
