#!/usr/bin/env bash
# Displays numbers 1-20 and bl from China 4, bl from Japan 9, and bl from Italy 17
counter=1
while [ $counter -le 20 ]
do
	echo "$counter"
	case $counter in
		4)
			echo "bad luck from China"
			;;
		9)
			echo "bad luck from Japan"
			;;
		17)
			echo "bad luck from Italy"
			;;
		esac
		(( counter++ ))
done
